### ISSUE TITLE
 cuda10 is not compatible with torch below 1.0

### ISSUE THREAD

**Issue by Anniessq** [Yochengliu/Relation-Shape-CNN#22]
Dear author:
 I want to ask that if your code run at cuda10?
If can't, should I change your code to torch1.0,or change my cuda to lower version?

Thank your for you work! Looking forward to your reply！

**Comment by Yochengliu** [comment]
Great!

**Comment by Anniessq** [comment]
> 
> 
> I have successfully run the code with cuda 10

May I ask you which version of pytorch have you installed ?

**Comment by sheshap** [comment]
> I have successfully run the code with cuda 10

Please let us know what are the configurations you used to run it on cuda 10

**Comment by LuckyQingq** [comment]
> I have successfully run the code with cuda 10

Could you give us the configurations you use? Thank you ahead!

**Comment by Holycomfort** [comment]
My solution is (with cuda10.1):
1. rm -rf build
2. mkdir build && cd build
3. cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda ..
4. make

**Comment by pixar0407** [comment]
> My solution is (with cuda10.1):
> 
> 1. rm -rf build
> 2. mkdir build && cd build
> 3. cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda ..
> 4. make

@Holycomfort 
Can you let me know your python version?

I got this error

> raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")

my configuration is 
cuda : 10.0.110
torch : 1.4.0
python : 3.7.10
conda : 4.8.3

thank you.

**Comment by pixar0407** [comment]
@crazy-bot 
> I have deleted the conda environment. As far I remember it was pytorch 1.3.1

hello, did you have any problem with using torch 1.3.1 related to ffi error?
i got this error 

> Traceback (most recent call last):
>   File "/home/ygkim/point_cloud/Relation-Shape-CNN/utils/build_ffi.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/home/ygkim/anaconda3/envs/rscnn4/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.


people tell me that this error comes from torch version mis-match. they say we should use torch version 0.4.1...
how did you do it?

**Comment by meamm** [comment]
@pixar0407 Have you solved this problem?

> raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")

I also encountered the same error
