### ISSUE TITLE
Bug coming from pointnet2utils

### ISSUE THREAD

**Issue by tchaton** [Yochengliu/Relation-Shape-CNN#28]
Dear @Yochengliu ,

Do you have any idea where it is coming from ?

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "train_partseg.py", line 207, in <module>
    main()
  File "train_partseg.py", line 92, in main
    train(train_dataloader, test_dataloader, model, criterion, optimizer, lr_scheduler, bnm_scheduler, args, num_batch)
  File "train_partseg.py", line 121, in train
    pred = model(points, batch_one_hot_cls)
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/thomas/HELIX/research/Relation-Shape-CNN/models/rscnn_msn_seg.py", line 142, in forward
    li_xyz, li_features = self.SA_modules[i](l_xyz[i], l_features[i])
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/thomas/HELIX/research/Relation-Shape-CNN/models/../utils/pointnet2_modules.py", line 51, in forward
    new_features
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/thomas/HELIX/research/Relation-Shape-CNN/models/../utils/pytorch_utils/pytorch_utils.py", line 67, in forward
    h_xi_xj = self.mapping_func2(self.activation(self.bn_mapping(self.mapping_func1(h_xi_xj))))
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663

**Comment by sausagecy** [comment]
you may check the variable 'batch_one_hot_cls' if it has correct dimensions or the value is right; I came across similar error (in classification task) because the label values are not from 0 to num_classes-1

**Comment by sausagecy** [comment]
you may check the variable 'batch_one_hot_cls' to see if it has correct dimensions or the values are right; I came across similar error (in classification task) because the label values ranges from 1 to num_classes (they should range from 0 to num_classes-1)
